<?php

/*
|--------------------------------------------------------------------------
| Frequently asked questions (single source of truth)
|--------------------------------------------------------------------------
| Rendered on the dedicated /faq page (with FAQPage JSON-LD) and, in a
| trimmed form, on the home page. Keeping the copy here means both stay in
| sync and there's one place to edit.
*/

return [

    'general' => [
        ['q' => 'How to use Apna Invoice, step by step?', 'a' => "1. Sign up free at apnainvoice.com. Continue with Google, or enter your mobile, email and password and verify the one-time code we send. No credit card.\n\n2. Add your business once: name, GSTIN, address, state. The state decides CGST + SGST (same state) or IGST (different state) automatically.\n\n3. Add your first customer. Name and state are required; GSTIN is optional for B2C. You can also click '+ New' on any invoice to add a customer inline (no page refresh, no lost data).\n\n4. Click 'New invoice', pick the customer, then type description, HSN/SAC, qty, rate and GST%. Defaults to GST 18%, qty 1.\n\n5. Click 'Issue'. The invoice locks, gets a permanent number (auto-resets every 1 April), and the PDF is generated. Goods invoices auto-print 3 copies (Original, Duplicate-Transporter, Triplicate-Supplier) per CGST Rule 48.\n\n6. Share on WhatsApp (pre-filled message), Email (PDF attached), or copy a 30-day public link. UPI QR is included if you've added a UPI ID.\n\n7. Record payment when received: full or part payment, with TDS support. The receipt PDF is generated automatically.\n\n8. At month-end, download the GSTR-1 CSV, GSTR-3B summary, receivables aging report, or a full ZIP backup from the dashboard.\n\nTip: Install Apna Invoice as a phone app via Chrome's 'Install' menu. It works like a native app."],
        ['q' => 'How can I create a GST invoice online for free in India?', 'a' => "Sign up on Apna Invoice (continue with Google or verify your mobile, no card required), add your business GSTIN and state once, then create your first GST invoice in about 60 seconds. The tool auto-calculates CGST + SGST for intra-state and IGST for inter-state supplies, supports HSN/SAC codes, and exports a GST-compliant tax invoice as PDF. It's completely free for unlimited invoices during beta."],
        ['q' => 'Is Apna Invoice the best free GST invoice generator for freelancers and small businesses in India?', 'a' => "We're built specifically for Indian freelancers, MSMEs, SMEs, startups, small shops and CAs. Apna Invoice is fully online (no installation), zero-cost, with India-first defaults: Indian numbering (lakhs and crores), GST slabs pre-loaded, FY-reset invoice numbers, UPI QR on every invoice, and one-click WhatsApp share, with no per-invoice or per-user limit."],
        ['q' => 'Does the invoice generator include HSN/SAC code and auto GST calculation?', 'a' => "Yes. Every line item has an HSN/SAC field with a built-in search link to the official GST portal, and you pick the GST rate (0%, 0.10%, 0.25%, 3%, 5%, 12%, 18%, 28%) per item. We auto-split CGST/SGST or IGST based on customer state, round to the paisa, and print the rate on every line as Rule 46 requires."],
        ['q' => 'Can I use this as free billing software for a small shop or MSME?', 'a' => "Yes. Small shops, retail stores, MSMEs and SMEs across India use Apna Invoice as a simple GST billing tool to issue tax invoices, cash memos for over-the-counter sales, and credit notes, and to track payment status. It runs in any browser on any device, with no desktop software to install and no billing-machine hardware needed. Free during beta with unlimited invoices."],
        ['q' => 'Can I download a GST invoice format for free?', 'a' => "Every invoice you create on Apna Invoice exports to a CBIC-compliant GST tax invoice PDF, five professional template styles (Classic Navy, Executive Maroon, Minimal Slate, Mercantile Forest, Heritage Burgundy). The PDF includes GSTIN, HSN/SAC, CGST/SGST/IGST split, place of supply, amount in words, signature block and your bank/UPI details. No template downloads to fiddle with, just create and download."],
        ['q' => 'Are these invoices GST-compliant?', 'a' => "Yes. We include GSTIN, HSN/SAC codes, place of supply, CGST/SGST or IGST split, invoice number, and amount in words (Indian format, in lakhs and crores). The format aligns with CBIC's prescribed tax invoice requirements."],
        ['q' => 'Do I need to know the GST rate for each item?', 'a' => 'Yes, but we pre-load the standard slabs (0%, 0.10%, 0.25%, 3%, 5%, 12%, 18%, 28%). You pick one per line item; the system handles CGST/SGST or IGST math based on customer state.'],
        ['q' => "What's the difference between draft and final?", 'a' => 'Drafts are editable and have no invoice number yet. Once you issue it, the invoice gets a permanent number (e.g. INV-0001), becomes read-only, and is considered legally issued. You can still mark payments against issued invoices.'],
        ['q' => 'Can I issue credit notes against an issued invoice?', 'a' => "Yes. Credit notes follow the GST Section 34 format: reason code, reference to the original invoice, and CGST/SGST or IGST reversal. They flow through your books and are ready for GSTR-1 reporting."],
        ['q' => 'I already maintain books in spreadsheets or another tool. Is it hard to switch?', 'a' => "No setup migration required for most users. Add your company once, paste in customers as you bill them, and carry on. You keep your existing invoice numbering series (we don't force ours). You can also export your Apna Invoice data at any time as a ZIP of CSV files, so you're never locked in."],
        ['q' => 'Can I bill international clients?', 'a' => 'Not yet. Apna Invoice is built for Indian domestic GST invoicing in INR (₹) only. Export under LUT/Bond, SEZ supplies, and multi-currency billing are intentionally out of scope while we stay focused on MSMEs, SMEs, startups and freelancers billing within India.'],
        ['q' => 'What happens to my data?', 'a' => 'It lives in your account, on our servers in India. You can export your invoices and customer data any time. We never sell data to third parties.'],
        ['q' => 'Who builds this?', 'a' => 'Datasoft Technologies (DST) is an Indian software company focused on practical tools for modern businesses. This product is free during beta while we grow.'],
    ],

];
