<?php

/**
 * Professional invoice themes compliant with CBIC Rule 46 conventions for
 * Indian tax invoices. All themes share the same compliant layout — they
 * differ only in accent color, rule weight, and a subtle title treatment.
 * Nothing overrides the structural professionalism required for B2B use.
 */

return [

    'classic' => [
        'label' => 'Classic · Navy',
        'accent' => '#1e3a8a',
        'accent_soft' => '#eef3fc',
        'title_color' => '#1e3a8a',
        'title_size' => '22px',
        'title_letter_spacing' => '3px',
        'top_rule' => '3px solid #1e3a8a',
        'header_rule' => '2px solid #1e3a8a',
        'table_head_bg' => '#eef3fc',
        'table_head_color' => '#1e3a8a',
        'table_row_border' => '#dbe3f5',
        'divider' => '#d1d5db',
        'totals_border' => '1px solid #cbd5e1',
        'total_rule' => '2px solid #1e3a8a',
        'total_color' => '#1e3a8a',
        'pill_bg' => '#eef3fc',
        'pill_color' => '#1e3a8a',
        'pill_border' => '1px solid #c7d2fe',
        'body_color' => '#111827',
        'muted' => '#6b7280',
    ],

    'bold' => [
        'label' => 'Executive · Maroon',
        'accent' => '#7c2d12',
        'accent_soft' => '#fef2f2',
        'title_color' => '#7c2d12',
        'title_size' => '22px',
        'title_letter_spacing' => '3px',
        'top_rule' => '3px solid #7c2d12',
        'header_rule' => '2px solid #7c2d12',
        'table_head_bg' => '#fef2f2',
        'table_head_color' => '#7c2d12',
        'table_row_border' => '#fecaca',
        'divider' => '#d1d5db',
        'totals_border' => '1px solid #cbd5e1',
        'total_rule' => '2px solid #7c2d12',
        'total_color' => '#7c2d12',
        'pill_bg' => '#fef2f2',
        'pill_color' => '#7c2d12',
        'pill_border' => '1px solid #fecaca',
        'body_color' => '#111827',
        'muted' => '#6b7280',
    ],

    'minimal' => [
        'label' => 'Minimal · Slate',
        'accent' => '#334155',
        'accent_soft' => '#f8fafc',
        'title_color' => '#334155',
        'title_size' => '20px',
        'title_letter_spacing' => '1px',
        'top_rule' => '1px solid #334155',
        'header_rule' => '1px solid #cbd5e1',
        'table_head_bg' => 'transparent',
        'table_head_color' => '#475569',
        'table_row_border' => '#f1f5f9',
        'divider' => '#e2e8f0',
        'totals_border' => '1px solid #e2e8f0',
        'total_rule' => '1px solid #334155',
        'total_color' => '#111827',
        'pill_bg' => '#f1f5f9',
        'pill_color' => '#334155',
        'pill_border' => '1px solid #cbd5e1',
        'body_color' => '#334155',
        'muted' => '#64748b',
    ],

    'retail' => [
        'label' => 'Mercantile · Forest',
        'accent' => '#065f46',
        'accent_soft' => '#ecfdf5',
        'title_color' => '#065f46',
        'title_size' => '22px',
        'title_letter_spacing' => '3px',
        'top_rule' => '3px solid #065f46',
        'header_rule' => '2px solid #065f46',
        'table_head_bg' => '#ecfdf5',
        'table_head_color' => '#065f46',
        'table_row_border' => '#a7f3d0',
        'divider' => '#d1d5db',
        'totals_border' => '1px solid #cbd5e1',
        'total_rule' => '2px solid #065f46',
        'total_color' => '#065f46',
        'pill_bg' => '#ecfdf5',
        'pill_color' => '#065f46',
        'pill_border' => '1px solid #a7f3d0',
        'body_color' => '#111827',
        'muted' => '#6b7280',
    ],

    'warm' => [
        'label' => 'Heritage · Burgundy',
        'accent' => '#9f1239',
        'accent_soft' => '#fff1f2',
        'title_color' => '#9f1239',
        'title_size' => '22px',
        'title_letter_spacing' => '3px',
        'top_rule' => '4px double #9f1239',
        'header_rule' => '2px double #9f1239',
        'table_head_bg' => '#fff1f2',
        'table_head_color' => '#9f1239',
        'table_row_border' => '#fecdd3',
        'divider' => '#d1d5db',
        'totals_border' => '1px solid #cbd5e1',
        'total_rule' => '3px double #9f1239',
        'total_color' => '#9f1239',
        'pill_bg' => '#fff1f2',
        'pill_color' => '#9f1239',
        'pill_border' => '1px solid #fecdd3',
        'body_color' => '#111827',
        'muted' => '#6b7280',
    ],

];
