<?php

/**
 * Sober visual themes for the invoice PDF. Accents applied sparingly — thin rules,
 * subtle tints, bold where it counts. Every theme is designed to fit within a
 * single A4 page for a typical 5-8 line invoice.
 */

return [

    'classic' => [
        'label' => 'Classic',
        'accent' => '#1e3a8a',
        'accent_soft' => '#f1f5f9',
        'title_color' => '#1e3a8a',
        'title_size' => '22px',
        'title_transform' => 'uppercase',
        'title_letter_spacing' => '2px',
        'top_rule' => '2px solid #1e3a8a',
        'header_rule' => '1px solid #1e3a8a',
        'table_head_bg' => '#f8fafc',
        'table_head_color' => '#1e3a8a',
        'table_row_border' => '#e5e7eb',
        'divider' => '#e5e7eb',
        'totals_border' => '1px solid #cbd5e1',
        'total_rule' => '2px solid #1e3a8a',
        'total_color' => '#1e3a8a',
        'pill_bg' => '#f1f5f9',
        'pill_color' => '#1e3a8a',
        'pill_border' => '1px solid #cbd5e1',
        'font_family' => 'DejaVu Sans, sans-serif',
        'body_color' => '#1f2937',
        'muted' => '#6b7280',
    ],

    'bold' => [
        'label' => 'Bold',
        'accent' => '#c2410c',
        'accent_soft' => '#fff7ed',
        'title_color' => '#c2410c',
        'title_size' => '22px',
        'title_transform' => 'uppercase',
        'title_letter_spacing' => '3px',
        'top_rule' => '3px solid #c2410c',
        'header_rule' => '1px solid #c2410c',
        'table_head_bg' => '#fff7ed',
        'table_head_color' => '#c2410c',
        'table_row_border' => '#fed7aa',
        'divider' => '#fed7aa',
        'totals_border' => '1px solid #fed7aa',
        'total_rule' => '3px solid #c2410c',
        'total_color' => '#c2410c',
        'pill_bg' => '#fff7ed',
        'pill_color' => '#c2410c',
        'pill_border' => '1px solid #fed7aa',
        'font_family' => 'DejaVu Sans, sans-serif',
        'body_color' => '#1c1917',
        'muted' => '#78716c',
    ],

    'minimal' => [
        'label' => 'Minimal',
        'accent' => '#047857',
        'accent_soft' => '#f9fafb',
        'title_color' => '#047857',
        'title_size' => '20px',
        'title_transform' => 'none',
        'title_letter_spacing' => '0',
        'top_rule' => '1px solid #d1fae5',
        'header_rule' => '1px solid #e5e7eb',
        'table_head_bg' => 'transparent',
        'table_head_color' => '#047857',
        'table_row_border' => '#f3f4f6',
        'divider' => '#e5e7eb',
        'totals_border' => 'none',
        'total_rule' => '1px solid #047857',
        'total_color' => '#047857',
        'pill_bg' => '#ffffff',
        'pill_color' => '#047857',
        'pill_border' => '1px solid #a7f3d0',
        'font_family' => 'DejaVu Sans, sans-serif',
        'body_color' => '#374151',
        'muted' => '#9ca3af',
    ],

    'retail' => [
        'label' => 'Retail',
        'accent' => '#0f172a',
        'accent_soft' => '#f8fafc',
        'title_color' => '#0f172a',
        'title_size' => '22px',
        'title_transform' => 'uppercase',
        'title_letter_spacing' => '3px',
        'top_rule' => '2px solid #0f172a',
        'header_rule' => '1px dashed #94a3b8',
        'table_head_bg' => '#f1f5f9',
        'table_head_color' => '#0f172a',
        'table_row_border' => '#e2e8f0',
        'divider' => '#cbd5e1',
        'totals_border' => '1px dashed #cbd5e1',
        'total_rule' => '2px solid #0f172a',
        'total_color' => '#0f172a',
        'pill_bg' => '#f1f5f9',
        'pill_color' => '#0f172a',
        'pill_border' => '1px dashed #94a3b8',
        'font_family' => 'DejaVu Sans Mono, monospace',
        'body_color' => '#0f172a',
        'muted' => '#64748b',
    ],

    'warm' => [
        'label' => 'Warm',
        'accent' => '#b91c1c',
        'accent_soft' => '#fef2f2',
        'title_color' => '#b91c1c',
        'title_size' => '22px',
        'title_transform' => 'uppercase',
        'title_letter_spacing' => '2px',
        'top_rule' => '2px double #b91c1c',
        'header_rule' => '1px solid #fecaca',
        'table_head_bg' => '#fef2f2',
        'table_head_color' => '#b91c1c',
        'table_row_border' => '#fee2e2',
        'divider' => '#fecaca',
        'totals_border' => '1px solid #fecaca',
        'total_rule' => '2px double #b91c1c',
        'total_color' => '#b91c1c',
        'pill_bg' => '#fef2f2',
        'pill_color' => '#b91c1c',
        'pill_border' => '1px solid #fecaca',
        'font_family' => 'DejaVu Sans, sans-serif',
        'body_color' => '#44403c',
        'muted' => '#a8a29e',
    ],

];
